# Generated by Django 4.1.6 on 2023-02-28 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Discussions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='file',
            field=models.ImageField(blank=True, upload_to='files'),
        ),
    ]
