# Generated by Django 4.1.6 on 2023-02-28 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Discussions', '0003_remove_discussion_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discussion',
            old_name='author',
            new_name='name',
        ),
    ]
